/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-08-21 15:27:30 UTC)
 * on 2013-08-23 at 18:33:52 UTC 
 * Modify at your own risk.
 */

package com.appspot.planetwarapi.status.model;

/**
 * Model definition for GeneratedStatus.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GeneratedStatus extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String gameDraw;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String gameLost;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String gameWin;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGameDraw() {
    return gameDraw;
  }

  /**
   * @param gameDraw gameDraw or {@code null} for none
   */
  public GeneratedStatus setGameDraw(java.lang.String gameDraw) {
    this.gameDraw = gameDraw;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGameLost() {
    return gameLost;
  }

  /**
   * @param gameLost gameLost or {@code null} for none
   */
  public GeneratedStatus setGameLost(java.lang.String gameLost) {
    this.gameLost = gameLost;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGameWin() {
    return gameWin;
  }

  /**
   * @param gameWin gameWin or {@code null} for none
   */
  public GeneratedStatus setGameWin(java.lang.String gameWin) {
    this.gameWin = gameWin;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public GeneratedStatus setUserId(java.lang.String userId) {
    this.userId = userId;
    return this;
  }

  @Override
  public GeneratedStatus set(String fieldName, Object value) {
    return (GeneratedStatus) super.set(fieldName, value);
  }

  @Override
  public GeneratedStatus clone() {
    return (GeneratedStatus) super.clone();
  }

}
