/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-08-21 15:27:30 UTC)
 * on 2013-08-23 at 18:33:22 UTC 
 * Modify at your own risk.
 */

package com.appspot.planetwarapi.user;

/**
 * Service definition for User (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link UserRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class User extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.15.0-rc of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://planetwarapi.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "user/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public User(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  User(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the UserController collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code User user = new User(...);}
   *   {@code User.UserController.List request = user.userController().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public UserController userController() {
    return new UserController();
  }

  /**
   * The "userController" collection of methods.
   */
  public class UserController {

    /**
     * Create a request for the method "userController.buyMerchandise".
     *
     * This request holds the parameters needed by the the user server.  After setting any optional
     * parameters, call the {@link BuyMerchandise#execute()} method to invoke the remote operation.
     *
     * @param idUser
     * @param content the {@link com.appspot.planetwarapi.user.model.MerchandisePurchased}
     * @return the request
     */
    public BuyMerchandise buyMerchandise(java.lang.Long idUser, com.appspot.planetwarapi.user.model.MerchandisePurchased content) throws java.io.IOException {
      BuyMerchandise result = new BuyMerchandise(idUser, content);
      initialize(result);
      return result;
    }

    public class BuyMerchandise extends UserRequest<com.appspot.planetwarapi.user.model.CollectionResponseMerchandiseUser> {

      private static final String REST_PATH = "buyMerchandise/{idUser}";

      /**
       * Create a request for the method "userController.buyMerchandise".
       *
       * This request holds the parameters needed by the the user server.  After setting any optional
       * parameters, call the {@link BuyMerchandise#execute()} method to invoke the remote operation.
       * <p> {@link BuyMerchandise#initialize(com.google.api.client.googleapis.services.AbstractGoogleCl
       * ientRequest)} must be called to initialize this instance immediately after invoking the
       * constructor. </p>
       *
       * @param idUser
       * @param content the {@link com.appspot.planetwarapi.user.model.MerchandisePurchased}
       * @since 1.13
       */
      protected BuyMerchandise(java.lang.Long idUser, com.appspot.planetwarapi.user.model.MerchandisePurchased content) {
        super(User.this, "POST", REST_PATH, content, com.appspot.planetwarapi.user.model.CollectionResponseMerchandiseUser.class);
        this.idUser = com.google.api.client.util.Preconditions.checkNotNull(idUser, "Required parameter idUser must be specified.");
      }

      @Override
      public BuyMerchandise setAlt(java.lang.String alt) {
        return (BuyMerchandise) super.setAlt(alt);
      }

      @Override
      public BuyMerchandise setFields(java.lang.String fields) {
        return (BuyMerchandise) super.setFields(fields);
      }

      @Override
      public BuyMerchandise setKey(java.lang.String key) {
        return (BuyMerchandise) super.setKey(key);
      }

      @Override
      public BuyMerchandise setOauthToken(java.lang.String oauthToken) {
        return (BuyMerchandise) super.setOauthToken(oauthToken);
      }

      @Override
      public BuyMerchandise setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (BuyMerchandise) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public BuyMerchandise setQuotaUser(java.lang.String quotaUser) {
        return (BuyMerchandise) super.setQuotaUser(quotaUser);
      }

      @Override
      public BuyMerchandise setUserIp(java.lang.String userIp) {
        return (BuyMerchandise) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long idUser;

      /**

       */
      public java.lang.Long getIdUser() {
        return idUser;
      }

      public BuyMerchandise setIdUser(java.lang.Long idUser) {
        this.idUser = idUser;
        return this;
      }

      @Override
      public BuyMerchandise set(String parameterName, Object value) {
        return (BuyMerchandise) super.set(parameterName, value);
      }
    }

  }

  /**
   * Create a request for the method "add".
   *
   * This request holds the parameters needed by the the user server.  After setting any optional
   * parameters, call the {@link Add#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.planetwarapi.user.model.UserApi}
   * @return the request
   */
  public Add add(com.appspot.planetwarapi.user.model.UserApi content) throws java.io.IOException {
    Add result = new Add(content);
    initialize(result);
    return result;
  }

  public class Add extends UserRequest<com.appspot.planetwarapi.user.model.UserApi> {

    private static final String REST_PATH = "add";

    /**
     * Create a request for the method "add".
     *
     * This request holds the parameters needed by the the user server.  After setting any optional
     * parameters, call the {@link Add#execute()} method to invoke the remote operation. <p> {@link
     * Add#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must be
     * called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.planetwarapi.user.model.UserApi}
     * @since 1.13
     */
    protected Add(com.appspot.planetwarapi.user.model.UserApi content) {
      super(User.this, "POST", REST_PATH, content, com.appspot.planetwarapi.user.model.UserApi.class);
    }

    @Override
    public Add setAlt(java.lang.String alt) {
      return (Add) super.setAlt(alt);
    }

    @Override
    public Add setFields(java.lang.String fields) {
      return (Add) super.setFields(fields);
    }

    @Override
    public Add setKey(java.lang.String key) {
      return (Add) super.setKey(key);
    }

    @Override
    public Add setOauthToken(java.lang.String oauthToken) {
      return (Add) super.setOauthToken(oauthToken);
    }

    @Override
    public Add setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Add) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Add setQuotaUser(java.lang.String quotaUser) {
      return (Add) super.setQuotaUser(quotaUser);
    }

    @Override
    public Add setUserIp(java.lang.String userIp) {
      return (Add) super.setUserIp(userIp);
    }

    @Override
    public Add set(String parameterName, Object value) {
      return (Add) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getAllUser".
   *
   * This request holds the parameters needed by the the user server.  After setting any optional
   * parameters, call the {@link GetAllUser#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public GetAllUser getAllUser() throws java.io.IOException {
    GetAllUser result = new GetAllUser();
    initialize(result);
    return result;
  }

  public class GetAllUser extends UserRequest<com.appspot.planetwarapi.user.model.CollectionResponseUserApi> {

    private static final String REST_PATH = "collectionresponse_userapi";

    /**
     * Create a request for the method "getAllUser".
     *
     * This request holds the parameters needed by the the user server.  After setting any optional
     * parameters, call the {@link GetAllUser#execute()} method to invoke the remote operation. <p>
     * {@link
     * GetAllUser#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetAllUser() {
      super(User.this, "GET", REST_PATH, null, com.appspot.planetwarapi.user.model.CollectionResponseUserApi.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetAllUser setAlt(java.lang.String alt) {
      return (GetAllUser) super.setAlt(alt);
    }

    @Override
    public GetAllUser setFields(java.lang.String fields) {
      return (GetAllUser) super.setFields(fields);
    }

    @Override
    public GetAllUser setKey(java.lang.String key) {
      return (GetAllUser) super.setKey(key);
    }

    @Override
    public GetAllUser setOauthToken(java.lang.String oauthToken) {
      return (GetAllUser) super.setOauthToken(oauthToken);
    }

    @Override
    public GetAllUser setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetAllUser) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetAllUser setQuotaUser(java.lang.String quotaUser) {
      return (GetAllUser) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetAllUser setUserIp(java.lang.String userIp) {
      return (GetAllUser) super.setUserIp(userIp);
    }

    @Override
    public GetAllUser set(String parameterName, Object value) {
      return (GetAllUser) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getData".
   *
   * This request holds the parameters needed by the the user server.  After setting any optional
   * parameters, call the {@link GetData#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetData getData(java.lang.Long id) throws java.io.IOException {
    GetData result = new GetData(id);
    initialize(result);
    return result;
  }

  public class GetData extends UserRequest<com.appspot.planetwarapi.user.model.UserApi> {

    private static final String REST_PATH = "userapi/{id}";

    /**
     * Create a request for the method "getData".
     *
     * This request holds the parameters needed by the the user server.  After setting any optional
     * parameters, call the {@link GetData#execute()} method to invoke the remote operation. <p>
     * {@link
     * GetData#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetData(java.lang.Long id) {
      super(User.this, "GET", REST_PATH, null, com.appspot.planetwarapi.user.model.UserApi.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetData setAlt(java.lang.String alt) {
      return (GetData) super.setAlt(alt);
    }

    @Override
    public GetData setFields(java.lang.String fields) {
      return (GetData) super.setFields(fields);
    }

    @Override
    public GetData setKey(java.lang.String key) {
      return (GetData) super.setKey(key);
    }

    @Override
    public GetData setOauthToken(java.lang.String oauthToken) {
      return (GetData) super.setOauthToken(oauthToken);
    }

    @Override
    public GetData setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetData) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetData setQuotaUser(java.lang.String quotaUser) {
      return (GetData) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetData setUserIp(java.lang.String userIp) {
      return (GetData) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetData setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetData set(String parameterName, Object value) {
      return (GetData) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateData".
   *
   * This request holds the parameters needed by the the user server.  After setting any optional
   * parameters, call the {@link UpdateData#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public UpdateData updateData() throws java.io.IOException {
    UpdateData result = new UpdateData();
    initialize(result);
    return result;
  }

  public class UpdateData extends UserRequest<com.appspot.planetwarapi.user.model.UserApi> {

    private static final String REST_PATH = "userapi";

    /**
     * Create a request for the method "updateData".
     *
     * This request holds the parameters needed by the the user server.  After setting any optional
     * parameters, call the {@link UpdateData#execute()} method to invoke the remote operation. <p>
     * {@link
     * UpdateData#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected UpdateData() {
      super(User.this, "GET", REST_PATH, null, com.appspot.planetwarapi.user.model.UserApi.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public UpdateData setAlt(java.lang.String alt) {
      return (UpdateData) super.setAlt(alt);
    }

    @Override
    public UpdateData setFields(java.lang.String fields) {
      return (UpdateData) super.setFields(fields);
    }

    @Override
    public UpdateData setKey(java.lang.String key) {
      return (UpdateData) super.setKey(key);
    }

    @Override
    public UpdateData setOauthToken(java.lang.String oauthToken) {
      return (UpdateData) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateData setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateData) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateData setQuotaUser(java.lang.String quotaUser) {
      return (UpdateData) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateData setUserIp(java.lang.String userIp) {
      return (UpdateData) super.setUserIp(userIp);
    }

    @Override
    public UpdateData set(String parameterName, Object value) {
      return (UpdateData) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link User}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link User}. */
    @Override
    public User build() {
      return new User(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link UserRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setUserRequestInitializer(
        UserRequestInitializer userRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(userRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
